version: '3.8'
services:
  api:
    build:
      context: ./api
      target: production
    container_name: api_backend

    ports:
      - '4000:4000'

  client:
    build:
      context: ./client
      target: production
    container_name: client_frontend
    ports:
      - '3000:3000'

# docker compose -f docker-compose.yml up -d --build